adobe_analytics.settings:
  type: config_object
  label: 'Adobe Analytics settings'
  mapping:
    role_tracking_type:
      type: string
      label: 'Role Tracking Type'
    js_file_location:
      type: string
      label: 'Javascript file location'
    codesnippet:
      type: string
      label: 'Codesnippet'
    version:
      type: string
      label: 'Version'
    image_file_location:
      type: string
      label: 'Image file location'
    token_cache_lifetime:
      type: integer
      label: 'Token cache lifetime'
    extra_variables:
      type: sequence
      label: 'Extra variables'
      sequence:
        type: adobe_analytics.variable
        label: 'Variable'
    track_roles:
      type: sequence
      label: 'Track roles'
      sequence:
        type: string
        label: 'Roles to track or not track'

adobe_analytics.variable:
  type: config_object
  label: 'Adobe Analytics variable'
  mapping:
    name:
      type: string
      label: 'Name'
    value:
      type: string
      label: 'Value'

field.value.adobe_analytics:
  type: mapping
  label: Default value
  mapping:
    include_custom_variables:
      type: boolean
      label: 'Include custom variables'
    include_main_codesnippet:
      type: boolean
      label: 'Include main code snippet'
    codesnippet:
      type: string
      label: 'Codesnippet'
